language: android
android:
  components:
    - android-23
    - build-tools-22.0.1
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew assemble test check